name: utils
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # DI
  kiwi: ^5.0.1
  # Routing
  go_router: ^15.1.2
  # State Management
  bloc: ^9.0.0
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  # Animations
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15
  bloc_test: ^10.0.0
